### ISSUE TITLE
Look at ESLint

### ISSUE THREAD

**Issue by Snugug** [Snugug/sass-lint#1]
So, I have no idea how to write a linter, but I think this should probably be based off of [ESLint](https://github.com/eslint/eslint), so I'm going to do that.

**Comment by xzyfer** [comment]
I have some experience in this area. Long story short you need to parse the source file into an [AST tree ](http://en.wikipedia.org/wiki/Abstract_syntax_tree). This produces a data structure which we can easily compare our rules against.

First things first we'll need a parser. There unfortunate aren't many parsers for Sass outside of the language implementations. I've been meaning to write one for a while now.

The one I am aware of is https://www.npmjs.com/package/gonzales-pe. It might also be worth looking to if/how scss-list is generating it's AST tree.

**Comment by Snugug** [comment]
Yah; I've played a little bit with lexers and parsers (but totally forgot about them without Googling!) Good to see that's the path I should be on!

I've found https://github.com/floby/node-parser, https://github.com/shfx/node-lexer, and https://github.com/aaditmshah/lexer (which looks the most promising to me).

One question think about; do we want this to be a strict port of `scss-lint`, or do we simply want to be compatible with it? I may lean towards the later as it would allow for things like a plugin system and, instead of just warning about property order, actually updating the source file with the respected ordering (or provide a more robust message that tells you what your property order actually needs to be)

**Comment by xzyfer** [comment]
I'd opt for the latter. Taking the ESLint approach of plugable rules is the mecca IMHO.

**Comment by Snugug** [comment]
Okay, good. We should change the name then so there isn't confusion. Maybe `sass-lint`?

**Comment by xzyfer** [comment]
I'm not sure how to approach this. I personally wanted to focus on the `scss` syntax. IMHO the old `sass` syntaxes adoption is declining and I'm not particularly keen on having two parsers initially.

**Comment by Snugug** [comment]
Oh, fully agree focus on `scss` first; I'm thinking Sass (the language), not `.sass`

**Comment by Snugug** [comment]
Sass lint?

**Comment by xzyfer** [comment]
Ah yeah, I meant to add I wanted to avoid potentially confusion, but maybe that's not an issue. Most people probably associate sass with .scss.

**Comment by Snugug** [comment]
I know I do. I'm going to go with that. If for no other reason than `scss-lint` already exists in `npm` as node bindings for the Ruby version. FWIW, Gonzales appears to work with `.sass` too

**Comment by xzyfer** [comment]
:+1:

**Comment by xzyfer** [comment]
I say we go lower case. Capital case is really awkward to me.

**Comment by Snugug** [comment]
Yah, it's lower case

**Comment by xzyfer** [comment]
The repo is currently `Sass-lint`

**Comment by Snugug** [comment]
Doh!

**Comment by xzyfer** [comment]
:cake: :tada:

**Comment by Snugug** [comment]
Closed in favor of #2
